stages:
  - fetch
  - build

jikesrvm:
  stage: fetch
  script:
    - sed -i 's,ssh://git,https://'$MMTK_TOKEN_NAME':'$MMTK_TOKEN_PASS',g' mmtk/Cargo.toml
    - JIKESRVM_REVISION=`cat jikesrvm/vm-revision`
    - git clone https://$JIKESRVM_TOKEN_NAME:$JIKESRVM_TOKEN_PASS@gitlab.anu.edu.au/mmtk/jikesrvm.git?rev=$JIKESRVM_REVISION
    - mkdir -f jikesrvm/rust_mmtk
    - cp mmtk/* jikesrvm/rust_mmtk/
  artifacts:
    paths:
      - jikesrvm

rbasebasenogc:
  stage: build
  script:
    - python jikesrvm/scripts/testMMTk.py -g RBaseBaseNoGC