stages:
  - build

build:
  stage: build
  script:
    - sed -i 's,ssh://git,https://'$DEPLOY_TOKEN_NAME':'$DEPLOY_TOKEN_PASS',g' mmtk/Cargo.toml
    - cargo +nightly build --manifest-path mmtk/Cargo.toml --features nogc --target=i686-unknown-linux-gnu
    - cargo +nightly build --manifest-path mmtk/Cargo.toml --features semispace --target=i686-unknown-linux-gnu
