name: Dacapo Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      # Checkout repos and submodules
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Rust Toolchain
        run: echo "RUSTUP_TOOLCHAIN=`cat mmtk/rust-toolchain`" >> $GITHUB_ENV
      - name: Setup Environments
        run: ./.github/scripts/ci-setup.sh

      # Run the tests
      - name: Dacapo Tests
        run: ./.github/scripts/ci-test-assertions.sh
