name: Dacapo Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      # Checkout repos and submodules
      - uses: actions/checkout@v2
        with:
          # CI_ACCESS_TOKEN is a secret set with the repo
          token: ${{ secrets.CI_ACCESS_TOKEN }}
          submodules: true
      - name: Set credential for cargo dependency
        run: sed -i 's/ssh:\/\/git@github.com\/mmtk/https:\/\/qinsoon:${{ secrets.CI_ACCESS_TOKEN }}@github.com\/mmtk/g' mmtk/Cargo.toml          
      - name: Setup Rust Toolchain
        run: echo "RUSTUP_TOOLCHAIN=`cat mmtk/rust-toolchain`" >> $GITHUB_ENV        
      - name: Setup Environments
        run: ./.github/scripts/ci-setup.sh

      # Run the tests
      - name: Dacapo Tests
        run: ./.github/scripts/ci-test.sh