name: Dacapo Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      # Checkout repos and submodules
      - uses: actions/checkout@v2
        with:
          # CI_ACCESS_TOKEN is a secret set with the repo
          token: ${{ secrets.CI_ACCESS_TOKEN }}
          submodules: true
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2019-08-26
          components: clippy
          target: i686-unknown-linux-gnu
          # This overwrites the default toolchain with the toolchain specified above.
          override: true
      # Check if we have cached dacapo benchmark. If not, download it.
      - uses: actions/cache@v1
        id: dacapo-cache
        with:
          path: repos/jikesrvm/benchmarks
          key: dacapo-2006
      - name: Download Dacapo
        if: steps.dacapo-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p repos/jikesrvm/benchmarks
          wget https://downloads.sourceforge.net/project/dacapobench/archive/2006-10-MR2/dacapo-2006-10-MR2.jar -O repos/jikesrvm/benchmarks/dacapo-2006-10-MR2.jar
      # Install dependencies for JikesRVM
      - name: Install JikesRVM dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install build-essential gcc-multilib gettext bison -y
      # Check Toolchain Versions
      - name: Check Toolchain Versions
        run: |
          set -x
          java -version
          javac -version
          echo $JAVA_HOME
          cargo --version
          rustup toolchain list

      # Run limited tests for BaseBase builds
      - name: RBaseBaseNoGC
        run: |
          export RUSTUP_TOOLCHAIN=+nightly-2019-08-26
          cd repos/jikesrvm
          python scripts/testMMTk.py -j $JAVA_HOME -g RBaseBaseNoGC -a "Xms1024M Xmx1024M" -- --use-third-party-heap=../../ --use-third-party-build-configs=../../jikesrvm/build/configs --use-external-source=../../jikesrvm/rvm/src

      - name: RBaseBaseSemiSpace
        run: |
          export RUSTUP_TOOLCHAIN=+nightly-2019-08-26
          cd repos/jikesrvm
          python scripts/testMMTk.py -j $JAVA_HOME -g RBaseBaseSemiSpace -a "Xms75M Xmx75M" -- --use-third-party-heap=../../ --use-third-party-build-configs=../../jikesrvm/build/configs --use-external-source=../../jikesrvm/rvm/src

      # Run full benchmark tests for FastAdaptive builds
      - name: RFastAdaptiveNoGC
        run: |
          export RUSTUP_TOOLCHAIN=+nightly-2019-08-26
          cd repos/jikesrvm
          ./bin/buildit localhost RFastAdaptiveNoGC -j $JAVA_HOME --answer-yes --use-third-party-heap=../../ --use-third-party-build-configs=../../jikesrvm/build/configs --use-external-source=../../jikesrvm/rvm/src
          ./dist/RFastAdaptiveNoGC_x86_64-linux/rvm -Xms3G -Xmx3G -jar benchmarks/dacapo-2006-10-MR2.jar antlr
          ./dist/RFastAdaptiveNoGC_x86_64-linux/rvm -Xms3G -Xmx3G -jar benchmarks/dacapo-2006-10-MR2.jar fop
          ./dist/RFastAdaptiveNoGC_x86_64-linux/rvm -Xms3G -Xmx3G -jar benchmarks/dacapo-2006-10-MR2.jar luindex
          ./dist/RFastAdaptiveNoGC_x86_64-linux/rvm -Xms3G -Xmx3G -jar benchmarks/dacapo-2006-10-MR2.jar pmd

      - name: RFastAdaptiveSemiSpace
        run: |
          export RUSTUP_TOOLCHAIN=+nightly-2019-08-26
          cd repos/jikesrvm
          ./bin/buildit localhost RFastAdaptiveSemiSpace -j $JAVA_HOME --answer-yes --use-third-party-heap=../../ --use-third-party-build-configs=../../jikesrvm/build/configs --use-external-source=../../jikesrvm/rvm/src
          ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -jar benchmarks/dacapo-2006-10-MR2.jar antlr
          ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -jar benchmarks/dacapo-2006-10-MR2.jar bloat
          ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms150M -Xmx150M -jar benchmarks/dacapo-2006-10-MR2.jar eclipse
          ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -jar benchmarks/dacapo-2006-10-MR2.jar fop
          ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms200M -Xmx200M -jar benchmarks/dacapo-2006-10-MR2.jar hsqldb
          ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -jar benchmarks/dacapo-2006-10-MR2.jar jython
          ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -jar benchmarks/dacapo-2006-10-MR2.jar luindex
          ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -jar benchmarks/dacapo-2006-10-MR2.jar lusearch
          ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -jar benchmarks/dacapo-2006-10-MR2.jar pmd
          ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -jar benchmarks/dacapo-2006-10-MR2.jar xalan